services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony_db?serverVersion=8"

  web:
    image: nginx:latest
    container_name: symfony-web
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: symfony-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "8081:80"

volumes:
  db_data:
